### ISSUE TITLE
Sending digital address with `PersonDigitalAdresse` results in "Ugyldig innhold i forsendelse: Navn må være utfylt."

### ISSUE THREAD

**Issue by Anarcroth** [ks-no/ks-no.github.io#15]
Hi!
We are integrating with SvarUT through `ForsendelsesServiceV10`. We have some logic to differentiate between sending document for Print or as Digital. Sending Print documents is fine, but we are having trouble when sending them as Digital. If we create an `Adresse` and `Forsendelse` in the following way (simplified):

``` java
Adresse adresse = new Adresse();

PersonDigitalAdresse personDigitalAdresse = new PersonDigitalAdresse();
personDigitalAdresse.setFodselsNummer(presonalNumber);
adresse.setDigitalAdresse(personDigitalAdresse);

Forsendelse shipment = new Forsendelse();

shipment.setEksternReferanse(id);
shipment.setTittel(tittel);
shipment.setAvgivendeSystem(name);
shipment.setMottaker(adresse);
shipment.setKrevNiva4Innlogging(isRequire2FA());
shipment.setKryptert(false);
shipment.setKunDigitalLevering(true);
shipment.getDokumenter().add(dokument);
```

and then create a request in the following way (simplified):

``` java
JaxWsProxyFactoryBean factory = new JaxWsProxyFactoryBean();
factory.setServiceClass(ForsendelsesServiceV10.class);
factory.setAddress(svarUTServiceUrl);
factory.setUsername(username);
factory.setPassword(password);

Map<String,Object> props = new HashMap<>();
props.put("mtom-enabled", Boolean.TRUE);
factory.setProperties(props);

factory.getFeatures().add(new WSAddressingFeature());
ForsendelsesServiceV10 serviceV10 = (ForsendelsesServiceV10) factory.create();

Client proxy = ClientProxy.getClient(serviceV10);
HTTPConduit conduit = (HTTPConduit) proxy.getConduit();

HTTPClientPolicy httpClientPolicy = new HTTPClientPolicy();
httpClientPolicy.setConnectionTimeout(timeoutSeconds * 1000);
httpClientPolicy.setReceiveTimeout(timeoutSeconds * 1000);
conduit.setClient(httpClientPolicy);

serviceV10.sendForsendelse(shipment);
```

As a result, the following validation error is returned to us:

```
Caused by: org.apache.cxf.binding.soap.SoapFault: Ugyldig innhold i forsendelse: Navn må være utfylt.
	at org.apache.cxf.binding.soap.interceptor.Soap11FaultInInterceptor.unmarshalFault(Soap11FaultInInterceptor.java:75) ~[cxf-rt-bindings-soap-2.7.2.jar:2.7.2]
	at org.apache.cxf.binding.soap.interceptor.Soap11FaultInInterceptor.handleMessage(Soap11FaultInInterceptor.java:46) ~[cxf-rt-bindings-soap-2.7.2.jar:2.7.2]
	at org.apache.cxf.binding.soap.interceptor.Soap11FaultInInterceptor.handleMessage(Soap11FaultInInterceptor.java:35) ~[cxf-rt-bindings-soap-2.7.2.jar:2.7.2]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:271) ~[cxf-api-2.7.2.jar:2.7.2]
	at org.apache.cxf.interceptor.AbstractFaultChainInitiatorObserver.onMessage(AbstractFaultChainInitiatorObserver.java:114) ~[cxf-api-2.7.2.jar:2.7.2]
	at org.apache.cxf.binding.soap.interceptor.CheckFaultInterceptor.handleMessage(CheckFaultInterceptor.java:69) ~[cxf-rt-bindings-soap-2.7.2.jar:2.7.2]
	at org.apache.cxf.binding.soap.interceptor.CheckFaultInterceptor.handleMessage(CheckFaultInterceptor.java:34) ~[cxf-rt-bindings-soap-2.7.2.jar:2.7.2]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:271) ~[cxf-api-2.7.2.jar:2.7.2]
	at org.apache.cxf.endpoint.ClientImpl.onMessage(ClientImpl.java:800) ~[cxf-api-2.7.2.jar:2.7.2]
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponseInternal(HTTPConduit.java:1590) ~[cxf-rt-transports-http-2.7.2.jar:2.7.2]
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponse(HTTPConduit.java:1488) ~[cxf-rt-transports-http-2.7.2.jar:2.7.2]
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.close(HTTPConduit.java:1307) ~[cxf-rt-transports-http-2.7.2.jar:2.7.2]
	at org.apache.cxf.transport.AbstractConduit.close(AbstractConduit.java:56) ~[cxf-api-2.7.2.jar:2.7.2]
	at org.apache.cxf.transport.http.HTTPConduit.close(HTTPConduit.java:622) ~[cxf-rt-transports-http-2.7.2.jar:2.7.2]
	at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:62) ~[cxf-api-2.7.2.jar:2.7.2]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:271) ~[cxf-api-2.7.2.jar:2.7.2]
	at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:530) ~[cxf-api-2.7.2.jar:2.7.2]
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:463) ~[cxf-api-2.7.2.jar:2.7.2]
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:366) ~[cxf-api-2.7.2.jar:2.7.2]
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:319) ~[cxf-api-2.7.2.jar:2.7.2]
	at org.apache.cxf.frontend.ClientProxy.invokeSync(ClientProxy.java:96) ~[cxf-rt-frontend-simple-2.7.2.jar:2.7.2]
	at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:133) ~[cxf-rt-frontend-jaxws-2.7.2.jar:2.7.2]
	at com.sun.proxy.$Proxy199.sendForsendelse(Unknown Source) ~[?:?]
        ...
	... 7 more
```

---

Maybe we have missed something? The `PersonDigitalAdresse` instance doesn't allow for a `Navn` to be set (it can only be put when creating a `PostAdresse`). 

When checking the documentation, it mentions that 
> The Digital Delivery only field has been removed and replaced with the Delivery Method field, which is of the Delivery Method type. This field is required and Delivery Method has three values: STANDARD_SPENDED_DELIVERY, ONLY_DIGITAL_UTEN_DELIVERY GUARANTEE and ONLY_DIGITAL_UTEN_DELIVERY GUARANTEE_MASS SHIPPING

But this is for version *11*, we can only use *10* for now.

---

We did try to also add to the `Adresse` object a `PostAdresse` one with only a name specified and it *did work*, but it didn't look right to both have `PostAdresse` and `PersonDigitalAdresse` at the same time. 

---

What is the proper way for sending documents for digital handling?

**Comment by andersflemmen** [comment]
Hello, you have to set the name on postAdresse:
```
Adresse adresse = new Adresse();

PersonDigitalAdresse personDigitalAdresse = new PersonDigitalAdresse();
personDigitalAdresse.setFodselsNummer(presonalNumber);
adresse.setDigitalAdresse(personDigitalAdresse);

PostAdresse postAdresse = new PostAdresse();
postAdresse.setNavn("Ola Nordmann");
adresse..setPostAdresse(postAdresse);
```

Understandable that this is somewhat confusing.

Hope this solves your problems!

**Comment by Anarcroth** [comment]
We did an experiment with it and it worked, but we were not sure that this was the right way to go about things.

Thank you very much for the quick reply, this fixes the issue :) :+1:
